fix: improve github actions (#15)
* fix: github actions

* fix: improvements

* ci: improve actions

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -3,17 +3,33 @@ name: Release
 on:
   push:
     branches: [main, staging, release]
+  workflow_dispatch:
+    inputs:
+      release:
+        type: choice
+        description: Release type to make
+        options: [alpha, rc, stable]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 
+permissions:
+  contents: write
+  pull-requests: write
+
+env:
+  RELEASE_TYPE: ${{ inputs.release || toJson('alpha') }}
+  RELEASE_ID: ${{ github.run_id }}
+
 jobs:
   setup:
     runs-on: ubuntu-latest
+    if: ${{ !startsWith(github.event.head_commit.message, 'ci(bump):') }}
     outputs:
-      prerelease: ${{ steps.set-prerelease.outputs.prerelease }}
-
+      prerelease: ${{ steps.set-vars.outputs.prerelease }}
+      branch: ${{ steps.set-branch.outputs.branch }}
+      changelog: ${{ steps.set-branch.outputs.changelog }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -23,24 +39,22 @@ jobs:
           git config --global user.name "${{ github.actor }}"
           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
 
-      - name: Check for pre-release configuration
-        id: set-prerelease
+      - name: Setting branch name
+        id: set-branch
         run: |
-          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
-            echo "prerelease=nightly" >> $GITHUB_OUTPUT
-          elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
-            echo "prerelease=rc" >> $GITHUB_OUTPUT
-          else
-            echo "prerelease=false" >> $GITHUB_OUTPUT
+          echo "branch=release/${{ env.RELEASE_TYPE }}-${{ env.RELEASE_ID }}" >> $GITHUB_OUTPUT
+
+      - name: Check for pre-release configuration
+        id: set-vars
+        run: |
+          type=${{ env.RELEASE_TYPE }}
+          echo "prerelease=$([[ "$type" != "stable" ]] && echo "$type" || echo "")" >> $GITHUB_OUTPUT
+          echo "changelog=$([[ "$type" == "stable" ]] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
 
   changelog:
     runs-on: ubuntu-latest
     needs: setup
-    outputs:
-      version: ${{ steps.save-outputs.outputs.version }}
-      changelog: ${{ steps.save-outputs.outputs.changelog }}
-      commit_message: ${{ steps.save-outputs.outputs.commit_message }}
-      branch: ${{ steps.save-outputs.outputs.branch }}
+    if: ${{ !startsWith(github.event.head_commit.message, 'ci(bump):') }}
 
     steps:
       - name: Checkout code
@@ -50,42 +64,26 @@ jobs:
         name: Create bump and changelog
         uses: commitizen-tools/commitizen-action@master
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          changelog_increment_filename: body.md
+          changelog: ${{ needs.setup.outputs.changelog }}
           prerelease: ${{ needs.setup.outputs.prerelease }}
+          push: false
+          commit: false
 
       - name: Save outputs
         id: save-outputs
         run: |
-          version=${{ steps.cz.outputs.version }}
-          changelog=$(cat body.md)
-          commit_message="ci(bump): release ${version}"
-          branch="release-${{ steps.cz.outputs.version }}"
-
-          echo "version=${version}" >> $GITHUB_OUTPUT
-          echo "changelog=${changelog}" >> $GITHUB_OUTPUT
+          commit_message="ci(bump): release ${{ env.REVISION }}"
           echo "commit_message=${commit_message}" >> $GITHUB_OUTPUT
-          echo "branch=${branch}" >> $GITHUB_OUTPUT
-
-  create_pr:
-    runs-on: ubuntu-latest
-    needs: changelog
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
 
       - name: Create Pull Request
         id: cpr
-        uses: peter-evans/create-pull-request@v3
+        uses: peter-evans/create-pull-request@v6
         with:
-          commit-message: ${{ needs.changelog.outputs.commit_message }}
-          title: Release ${{ needs.changelog.outputs.version }}
-          body: |
-            ${{ needs.changelog.outputs.changelog }}
-          branch: ${{ needs.changelog.outputs.branch }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          token: ${{ secrets.REPO_TOKEN }}
+          commit-message: ${{ steps.save-outputs.outputs.commit_message }}
+          title: ${{ steps.save-outputs.outputs.commit_message }}
+          branch: ${{ needs.setup.outputs.branch }}
+          body-path: ./tmp/body.md
 
       - name: Check outputs
         if: ${{ steps.cpr.outputs.pull-request-number }}
@@ -93,29 +91,32 @@ jobs:
           echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
           echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
 
-  release:
-    runs-on: ubuntu-latest
-    needs: changelog
-    if: github.ref == 'refs/heads/release'
+      - run: |
+          git push origin --tags
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Release
-        uses: softprops/action-gh-release@v1
-        with:
-          body_path: body.md
-          tag_name: ${{ needs.changelog.outputs.version }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  notify:
-    runs-on: ubuntu-latest
-    if: failure()
-
-    steps:
-      - name: Error Notification
-        run: |-
-          echo "An error occurred during the release process"
-          # Optionally, send a notification to Slack or email
+  # release:
+  #   runs-on: ubuntu-latest
+  #   needs: changelog
+  #   if: github.ref == 'refs/heads/release'
+  #
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #
+  #     - name: Release
+  #       uses: softprops/action-gh-release@v1
+  #       with:
+  #         body_path: body.md
+  #         tag_name: ${{ env.REVISION }}
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #
+  # notify:
+  #   runs-on: ubuntu-latest
+  #   if: failure()
+  #
+  #   steps:
+  #     - name: Error Notification
+  #       run: |-
+  #         echo "An error occurred during the release process"
+  #  # Optionally, send a notification to Slack or email
